# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
# https://github.com/kubernetes-sigs/headlamp/tree/main/charts/headlamp

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: headlamp

spec:
  releaseName: headlamp
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: headlamp
  interval: 50m
  install:
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: headlamp-values
      optional: true

  values:
    config:
      pluginsDir: /build/plugins

    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugins
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins

    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins

    volumes:
      - name: headlamp-plugins
        emptyDir: {}
