authentik:
  error_reporting:
    enabled: false
redis:
  enabled: true
postgresql:
  enabled: true
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - authentik.dev-cluster.local
