apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: headlamp.dev-cluster.local
          paths:
            - path: /
              type: ImplementationSpecific
