apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
  - namespace.yaml
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authentik-values
    files:
      - values.yaml

secretGenerator:
  - name: authentik-values
    files:
      - values.yaml=values.sops.yaml
