apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io/
    releaseName: authentik
    version: 2025.8.4
    valuesFile: ./values.yaml
