#!/usr/bin/env bash

# git config --local core.hooksPath .githooks

set -e

# Encrypt with sops before committing (then decrypt, "transparent" encryption!)
files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '.*\.sops\.yaml' || true)
for f in ${files[@]}; do
    [ -f "$f" ] || continue
    echo "Encrypting $f"
    sops -i -e "$f"
    git add "$f"
    sops -i -d "$f"
done
