creation_rules:
  - age:
      - age1s3cqcks5genc6ru8chl0hkkd04zmxvczsvdxq99ekffe4gmvjpzsedk23c
      - age1yg8cf7vv9nsfnc794ja3waxywm7ypjn5d4l3fv4seusjw79ueg0qyhe9f4
    path_regex: .*secret.*

stores:
  yaml:
    indent: 2
