apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
spec:
  project: default
  source:
    path: deploy/manifests/services/immich
  destination:
    name: "in-cluster"
    namespace: services-immich
