apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
spec:
  project: default
  sources:
    - repoURL: ghcr.io/immich-app/immich-charts
      chart: immich
      targetRevision: 0.10.0
      helm:
        valueFiles:
          - $values/deploy/manifests/services/immich/values.yaml
    - repoURL: https://github.com/nospawnn/homelab.git
      ref: values
    - repoURL: https://github.com/nospawnn/homelab.git
      path: deploy/manifests/services/immich
  destination:
    name: "in-cluster"
    namespace: immich
