# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: openebs-release

spec:
  releaseName: openebs
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs-repo
  interval: 50m
  install:
    remediation:
      retries: 3

  values:
    engines:
      replicated:
        mayastor:
          enabled: false
      local:
        zfs:
          enabled: false
    lvm-localpv:
      lvmNode:
        kubeletDir: /varlib/k0s/kubelet
    localpv-provisioner:
      hostpathClass:
        isDefaultClass: true
