- name: Deploy vikunja quadlet
  ansible.builtin.include_role:
    name: quadlet
  vars:
    quadlet_state: present
    quadlet_enabled: true

    quadlet_src_dir: "{{ app_src_dir }}/services/vikunja"
    quadlet_app_name: vikunja
