- name: Deploy vikunja quadlet
  ansible.builtin.include_role:
    name: quadlet
  vars:
    quadlet_state: absent
    quadlet_enabled: true

    quadlet_app_src_dir: "../../apps/services/vikunja"
    quadlet_app_name: vikunja
