apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cloudflare-tunnel
    repo: https://cloudflare.github.io/helm-charts
    releaseName: cloudflare-tunnel
    version: 0.3.2
    valuesFile: ./values.yaml
