apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - namespace.yaml
  - ../../../base/traefik

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml
