# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
# https://github.com/traefik/traefik-helm-chart/tree/master/traefik

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik

spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
  interval: 50m
  install:
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
      optional: true
    - kind: Secret
      name: traefik-values
      optional: true
