apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - repository.yaml
  - release.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: headlamp-values
    files:
      - values.yaml
