# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
# https://github.com/go-vikunja/helm-chart/blob/main/values.yaml

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vikunja

spec:
  releaseName: vikunja
  chart:
    spec:
      chart: vikunja
      sourceRef:
        kind: HelmRepository
        name: vikunja-repo
  interval: 50m
  install:
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: vikunja-values
      optional: true
    - kind: Secret
      name: vikunja-values
      optional: true
