# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
# https://github.com/goauthentik/helm/blob/main/charts/authentik

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: authentik

spec:
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
  interval: 50m
  install:
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: authentik-values
      optional: true
    - kind: Secret
      name: authentik-values-secret

  values:
    authentik:
      error_reporting:
        enabled: true
      postgresql:
    redis:
      enabled: true
    postgresql:
      enabled: true
