apiVersion: v1
kind: Pod
metadata:
  name: caddy
spec:
  containers:
    - image: ghcr.io/caddybuilds/caddy-cloudflare:2.10
      name: caddy
      ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
      volumeMounts:
        - mountPath: /etc/caddy:Z
          name: conf
  volumes:
    - name: conf
      hostPath:
        path: .
