- name: Ensure gitops dir is empty
  block:
    - name: Clear directory
      ansible.builtin.file:
        dest: /var/lib/gitops
        state: absent

    - name: Recreate directory
      ansible.builtin.file:
        dest: /var/lib/gitops
        state: directory
        owner: root
        group: root
        mode: "0644"

- name: Pull git repo
  ansible.builtin.git:
    repo: https://github.com/NoSpawnn/homelab.git
    dest: /var/lib/gitops
    version: master
    update: true

- name: Copy systemd unit
  ansible.builtin.copy:
    src: git-sync.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "0644"

- name: Copy systemd timer
  ansible.builtin.copy:
    src: git-sync@.timer
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "0644"

- name: Populate .vault_pass
  ansible.builtin.copy:
    dest: /var/lib/gitops/.vault_pass
    content: "{{ vault_password }}"
    mode: "0600"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Initial sync
  ansible.builtin.systemd:
    name: git-sync.service
    state: started

- name: Enable sync timer
  ansible.builtin.systemd:
    name: git-sync@10.timer
    state: started
    enabled: true
