- name: Install {{ quadlet_app_name }}
  ansible.builtin.include_tasks: install.yaml
  when: quadlet_state == "present"

- name: Remove {{ quadlet_app_name }}
  ansible.builtin.include_tasks: remove.yaml
  when: quadlet_state == "absent"
