- name: Stop and disable quadlet
  ansible.builtin.systemd:
    name: "{{ quadlet_app_name }}.service"
    state: stopped
    enabled: false
  ignore_errors: true

- name: Remove quadlet file
  ansible.builtin.file:
    path: "{{ quadlet_dest }}"
    state: absent
  notify:
    - Reload systemd

- name: Remove application files
  ansible.builtin.file:
    path: "{{ quadlet_app_dest_dir }}"
    state: absent
