- name: Deploy podman quadlet apps to localhost
  hosts: all
  connection: local
  tasks:
    - name: Configure {{ item }}
      ansible.builtin.import_role:
        name: "{{ item }}"
      loop: "{{ services }}"
