- name: Deploy podman quadlet apps to localhost
  hosts: all
  connection: local
  tasks:
    - name: Include services
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ services }}"
      loop_control:
        label: "{{ item }}"
