apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
spec:
  project: default
  source:
    repoURL: https://github.com/nospawnn/homelab.git
    path: deploy/manifests/infra/cloudflared
  destination:
    name: "in-cluster"
    namespace: tunnel
