apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - openebs/
  - apps.yaml

patches:
  - patch: |
      - op: add
        path: /spec/decryption
        value:
          provider: sops
          secretRef:
            name: sops-age
    target:
      kind: Kustomization
      namespace: flux-system
