- name: Deploy caddy quadlet
  ansible.builtin.include_role:
    name: quadlet
  vars:
    quadlet_state: present
    quadlet_enabled: true

    quadlet_src_dir: "{{ apps_src_dir }}/network/caddy"
    quadlet_app_name: caddy
    quadlet_app_files:
      - Caddyfile

    cloudflare_token: "{{ vault_caddy_cloudflare_token }}"
