apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vikunja

resources:
  - namespace.yaml
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: vikunja-values
    files:
      - values.yaml=values.yaml

secretGenerator:
  - name: vikunja-values
    files:
      - values.yaml=values.sops.yaml
