apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: headlamp

resources:
  - namespace.yaml
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: headlamp-values
    files:
      - values.yaml=values.yaml
