- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart {{ quadlet_app_name }}
  ansible.builtin.systemd:
    name: "{{ quadlet_app_name }}.service"
    state: restarted
    enabled: "{{ quadlet_enabled }}"
