# https://github.com/goauthentik/helm/blob/main/charts/authentik/values.yaml
authentik:
  # SECRET
  secret_key: ENC[AES256_GCM,data:r9ahQLPQZW+A9l0ZyCA53NOnd4W3rX7m2+tVEToF2FwtcnYRfUEQRfGDA+5tbB9YIRhch+VcH1q1zc3LrLpCNmCrqmjBnBYpAqY8g39YyDE=,iv:C1o/ukfTS8VioFCDSUI6V2Osr8n4hjZpUWtSrnyFVts=,tag:GtCdFt7jO9FGO4siVLHv0w==,type:str]
  error_reporting:
    enabled: true
  postgresql:
    # SECRET
    password: ENC[AES256_GCM,data:Eypnoofg92drlmm698iDEdM7qrzcxmiuZJAi6TpgO6F8JihIP+M4bWawM3b68PXgcU5pBtVUh4PextArI7FiogUc/lHw9qdonLJoOvJn/cg=,iv:4jKzNQ4sJd5uwOlkKLzYJNSaNc9BlNVRhQaXVuXrBXI=,tag:09+aw8/nX6KR7qFXsHyl4Q==,type:str]
redis:
  enabled: true
postgresql:
  enabled: true
  auth:
    # SECRET
    password: ENC[AES256_GCM,data:tQw7fJEGYpYhMlU/JBXwLgznzosU3x1L4SkcLaQo9XZuXtum2/E9xRBnOE3cey2eUh5kQPyeX1zBk+vSPwWMupG7kPYWZiiAADOqZ2qihCM=,iv:X8JKE8cj7aiql5qFQvWVXpJJYpdIo27TCHDkICmqYF4=,tag:vJKC1ah2jtiQtTMyKuD36Q==,type:str]
server:
  ingress:
    enabled: false
    hosts:
      - authentik.domain.tld
sops:
  age:
    - recipient: age1s3cqcks5genc6ru8chl0hkkd04zmxvczsvdxq99ekffe4gmvjpzsedk23c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ0RJalZWREpuanhzOWVR
        QS9hU0JINFl4VjJYUHRRclZkWmh2U1ppdVZJCjZNb2N5azdnMUhreTByZGl0MGxD
        V1pacHE3RzNyTUhEazhvSUN5RnJkd1kKLS0tIFFSZUI2Tlc1WmVCRkwyYmc3c0pZ
        MjN2bXU0em11M0V3VkN1V0RQWGkwY00KpZDV7KcW6Rjxh/sLTP8Z5ibdBlvuRc+d
        TZgxPKHGO+YaS9foYNVYK84AXYM+aaaC3ZdAqafMtIVvPjonsbX5cg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1yg8cf7vv9nsfnc794ja3waxywm7ypjn5d4l3fv4seusjw79ueg0qyhe9f4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UFozaFJFWTFjdHVjWmEy
        Y3BXczkyYktoSGxxRnZrcE5aM0Zzam1FVVNBCklBM01FL2oydE9DL1JKZFk2VWFt
        L3gwWk56NmVXSzlxckFUZDJNcFY3b2MKLS0tIDlHSCt5WTNIdW1DM2JKNnczMVFF
        NHJLQkxUZktpb2ZBbnV1ZjduZnJhODAK8AUi+gagS5i52LkTPgxlo+XfDLFuv4nK
        29RBFnBKnkEAFfvrme0zX69/enZ5UStJBQzQRECmtV45qC1pO5n3AA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-14T22:24:42Z"
  mac: ENC[AES256_GCM,data:qiRY7IaID5VI1horsL67HvpFzFuJ3G42PWp7hf52I8KmwJD9HYFgQYnChKtH8HuWE6m9LvidECeCjFumnbt7l6HRlEeu6Wg9l+VEmlhYX40UxBlanVi1aIdTfjq2VZ01PbZ7Qj+j1QNDaSSAtwTo3jJtObvLeawLSVWNe84Njzs=,iv:hjPnhmN4A5kSsOhf4jMvPkm+PP9pwY6u6ZYm2oNv+GQ=,tag:BRZ5myFE5/D57oy8B8dSUQ==,type:str]
  encrypted_comment_regex: SECRET
  version: 3.11.0
